# Generated by Django 3.2.6 on 2021-08-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_books_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.CharField(max_length=30000000),
        ),
        migrations.AlterField(
            model_name='books',
            name='subcategory',
            field=models.CharField(default='', max_length=500),
        ),
    ]
