# Generated by Django 3.2.6 on 2021-08-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210822_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='img1',
            field=models.ImageField(default='', upload_to='app/images'),
        ),
        migrations.AddField(
            model_name='books',
            name='img2',
            field=models.ImageField(default='', upload_to='app/images'),
        ),
        migrations.AddField(
            model_name='books',
            name='img3',
            field=models.ImageField(default='', upload_to='app/images'),
        ),
    ]
