# Generated by Django 3.2.6 on 2021-08-21 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210822_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='books',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='books',
            name='img3',
        ),
    ]
