# Generated by Django 3.2.6 on 2021-08-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='named',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
